### ISSUE TITLE
Error while enchanting

### ISSUE THREAD

**Issue by refaim** [laytya/AdvancedTradeSkillWindow-vanilla#22]
I opened ATSW enchanting window, opened a character window, enchanted my bracers for minor stamina and got this error:

```
AdvancedTradeSkillWindow\atsw.lua:427: Attempt to find 'this' in non-table object (used '.' instead of ':' ?)
<in C code>: in function `SetPortraitTexture'
AdvancedTradeSkillWindow\atsw.lua:427: in function `ATSWFrame_OnEvent'
<string>:"ATSWFrame:OnEvent":2: in main chunk
```

**Comment by laytya** [comment]
hm cant reproduce it. May be u have other addons customized CraftFrame?

**Comment by ghost** [comment]
I can reproduce this. Even with just ATSW and nothing else.

While Enchanting was open, if I changed some gear this error happens.
It looks like if I open up engi first, then enchanting, there is no error.

I suspect that the error itself is in FrameXML\UnitFrame.lua and not ATSW

But for now that's as far as I've gotten.
This bug is very strange.

**Comment by laytya** [comment]
Its not ATSW issue - code the same as in original TSW.... so its just client  issue...
